# Generated by Django 5.2.3 on 2025-06-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordereditem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
