# Generated by Django 5.2.1 on 2025-06-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year', models.IntegerField(null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='MovieInfo',
        ),
    ]
