# Generated by Django 5.2.1 on 2025-06-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieinformation_delete_director_delete_movieinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinformation',
            name='description',
            field=models.TextField(default='No summaries found'),
        ),
    ]
