# Generated by Django 5.2.1 on 2025-06-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movieinformation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinformation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movieinformation',
            name='year',
            field=models.IntegerField(),
        ),
    ]
