# Generated by Django 5.2.1 on 2025-06-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movieinformation_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieInformation',
            new_name='MovieDetails',
        ),
    ]
