# Generated by Django 5.2.1 on 2025-06-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_movieinformation_moviedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieDetails',
            new_name='MovieInformations',
        ),
    ]
