# Generated by Django 5.2.1 on 2025-06-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_moviedetails_movieinformations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieInformations',
            new_name='MovieInformation',
        ),
    ]
